### PR TITLE
Add twitter feed in content area

### PR DESCRIPTION
**Pull request by kingthorin**
Add zaproxy and zaproxybot twitter feed embedded in the content area.

See also: https://github.com/OWASP/www--site-theme/pull/77

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Screenshot_2021-03-04 OWASP ZAP

**Comment by psiinon** [comment]
How easy would it be to have the 2 feeds side by side in the main section underneath the zaproxy.org pic/link ? :)

**Comment by kingthorin** [comment]
I tried that, unfortunately they expand to fit the frame. I’ll have a deeper look at how they might be constrained.

**Comment by kingthorin** [comment]
I had to make it a local include to control the width, but that's not a big deal. Also for some reason if I had them at 50% it would stack them, hence 49% each and centered.
Screenshot_2021-03-05 OWASP ZAP

**Comment by psiinon** [comment]
Nice!

**Review by psiinon — APPROVED** [review]

**Comment by thc202** [comment]
The commit message and PR should be updated to reflect the latest position.

**Comment by thc202** [comment]
How does it look in mobile?

**Comment by kingthorin** [comment]
> 
> How does it look in mobile?

Seems okay in Firefox responsive design mode. In portrait orientation they stack, in landscape they're side-by-side. In both cases they seem to scale appropriately.

**Comment by kingthorin** [comment]
Messages tweaked.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
The messages are still the same though.

**Comment by kingthorin** [comment]
Old text:
> Use new twitter feed include to add zaproxy and zaproxybot twitter feed embeds to the side bar.

**Pull request merged**
