### PR TITLE
Remove zapcon banner

### PR DESCRIPTION
**Pull request by kingthorin**
- index.md > Remove zapcon details and image.
- info.md > Add zacon link to the sidebar.
- zapcon-banner.png > Removed, no longer needed.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Review by psiinon — APPROVED** [review]

**Comment by thc202** [comment]
There's a typo in the commit message (no), in case you want to fix it.

**Comment by kingthorin** [comment]
Ya I will, thanks!

**Comment by kingthorin** [comment]
Done

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
