### PR TITLE
Remove Unused "Assets"

### PR DESCRIPTION
**Pull request by kingthorin**
- Remove README.md from images directory, it was still being web deployed but it useless in the deployment, and it seems evident what the directory is for.
- Removed double extension "*.png.jpeg" images no longer being used.
- Remove 2013 top 10 related PDF and md which are no longer being used, as the content has been migrated to: https://www.zaproxy.org/docs/guides/zapping-the-top-10/

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by thc202** [comment]
The PDF is linked from `zappingthetop10.md`, although this page is no longer linked anywhere, remove as well?
The `zap-website.png` is used in `index.md`.

**Comment by kingthorin** [comment]
Oops, guess I was `del` happy. Tweak coming.

**Comment by kingthorin** [comment]
Fixed

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thanks!

**Review by psiinon — APPROVED** [review]

**Pull request merged**
