### PR TITLE
20th anniversary update

### PR DESCRIPTION
**Pull request by kingthorin**
Per request:
https://groups.google.com/a/owasp.org/g/leaders/c/CLYraRKBZCE

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by thc202** [comment]
Will the image fit correctly? Looks big.

**Review by thc202 — APPROVED** [review]

**Comment by kingthorin** [comment]
Ya it works out, I think it's scaled.

You can see it here: https://owasp.org/www-project-vulnerable-web-applications-directory/

**Comment by thc202** [comment]
Thank you.

**Comment by psiinon** [comment]
Is it the same as the VWAD one? That looks very big :/

**Comment by kingthorin** [comment]
Yup, I was just rolling with what’s been provided but I guess I could resize it.

75% ?

**Comment by psiinon** [comment]
I'm confused.
If its so important why is it not on the front page? That gets way more hits that any other pge, probably more than the rest combined :/

**Comment by kingthorin** [comment]
&lt;shrug&gt; I think that’s probably a question for the leaders list.

**Comment by psiinon** [comment]
Have asked :)
TBH I prefer how Juice Shop has done this, ie in the right hand tab: https://owasp.org/www-project-juice-shop/

**Comment by kingthorin** [comment]
Sure, we can do it that way as well. Will tweak this later.

**Comment by psiinon** [comment]
Thanks!

**Comment by kingthorin** [comment]
Re-jigged:
image

(It doesn't actually cut off like that, it's just how my VM screenshot worked out.)

**Comment by thc202** [comment]
LGTM.

**Review by psiinon — APPROVED** [review]

**Pull request merged**
